# Site Settings

title: j.l. feinstein 
tagline:
description:
defaults:


baseurl: ""
url: "https://jl-feinstein.jews.international"

date_format: "%B %d, %Y"

# Author Settings

author: J L Feinstein 
email: jl-feinstein@jews.international
social:
  - name: Facebook
    icon: facebook-square
    url: facebook.com/jl.feinstein.50
  - name: Mastodon
    icon: mastodon-square
    url: masto.jews.international/@derpayatz
  - name: Twitter
    icon: twitter-square
    url: twitter.com/derpayatz
  - name: Github
    icon: github-square
    url: github.com/derpayatz
    
# Front Matter Defaults

defaults:
  -
    scope:
      type: "posts"
    values:
      layout: "post"

# Markdown Settings

kramdown:
#  hard_wrap: true

# Build Settings

markdown: kramdown

plugins:
  - jekyll-feed
  - jekyll-responsive-image
  - jekyll-category-pages
  - jekyll-paginate

include: ['_pages']

# Serve Settings

host: localhost
port: 9001

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - .gitignore
  - .git/
  - README.md
  
# Plugin Settings

responsive_image:
  template: _includes/responsive-image.html
  default_quality: 90
  sizes:
    - width: 320
    - width: 512
    - width: 768
  strip: true
  output_path_format: assets/images/%{filename}-%{width}.%{extension}
  save_to_source: false
  cache: false

jekyll-category-pages:
  paginate: 2
  category_path: category
